stages:
  - build
  - migrate
  - deploy
  - swagger


.vars_prod: &vars_prod
  HARBOR_URL: harbor-prod.rbtdigitalmobile.ru
  HARBOR_USER: ${HARBOR_USER_PROD}
  HARBOR_PASS: ${HARBOR_PASSWORD_PROD}
  HARBOR_PROJECT: sandbox
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  RUNTIME_IMAGE: xxx
  KUBE_NAMESPACE: sandbox-${CI_ENVIRONMENT_NAME}
  KUBECONFIG: "/home/gitlab-runner/.kube/prod-mobi-gitlab.yaml"


.vars_dev: &vars_dev
  HARBOR_URL: harbor.rbt.ru
  HARBOR_USER: ${HARBOR_USER_DEV}
  HARBOR_PASS: ${HARBOR_PASSWORD_DEV}
  HARBOR_PROJECT: sandbox
  IMAGE_TAG: ${CI_COMMIT_SHA}
  RUNTIME_IMAGE: xxx
  KUBE_NAMESPACE: sandbox-${CI_ENVIRONMENT_NAME}

.docker_build_tpl:
  stage: build
  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - cd $CI_PROJECT_DIR/${BUILD_DIR}
    - docker login -u ${HARBOR_USER} -p ${HARBOR_PASS} https://${HARBOR_URL}
  script:
    - docker build . --tag ${HARBOR_URL}/${HARBOR_PROJECT}/${APP}:${IMAGE_TAG} 
    - docker push ${HARBOR_URL}/${HARBOR_PROJECT}/${APP}:${IMAGE_TAG}
  # after_script:
  #   - docker image rm $(docker image ls | grep ${HARBOR_URL}/${HARBOR_PROJECT} |  awk '{print$3}') || true
  #   - docker image prune -f

.migrate-db:
  stage: migrate
  script: 
    - cd ${CI_PROJECT_DIR}/store_migrate/changelog
    - liquibase --defaults-file=liquibase_${CI_ENVIRONMENT_NAME}.properties update

.rollback-db:
  stage: migrate
  when: manual
  # allow_failure: true 
  script: 
    - cd ${CI_PROJECT_DIR}/store_migrate/changelog
    - liquibase --defaults-file=liquibase_${CI_ENVIRONMENT_NAME}.properties rollback-count 1


.deploy_k8s:
  stage: deploy
  script:
    -  helm upgrade store-${APP}-${CI_ENVIRONMENT_NAME} .helm/${APP} --set global.env=${CI_ENVIRONMENT_NAME},image.tag=${IMAGE_TAG},image.repository=${HARBOR_URL}/${HARBOR_PROJECT} -n ${KUBE_NAMESPACE}

.deploy_swagger:
  stage: swagger
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  script:
    - helm upgrade swagger-${CI_ENVIRONMENT_NAME} .helm/swagger --set global.env=${CI_ENVIRONMENT_NAME} --install -n ${KUBE_NAMESPACE}

################################################################################################
################################################################################################
################################################################################################
################################################################################################

build-assembly-backend:
  extends: .docker_build_tpl
  variables:
    <<: *vars_dev
    APP: store-backend
    BUILD_DIR: store_backend
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/
      when: manual
  tags: 
    - shell

build-frontend:
  extends: .docker_build_tpl
  variables:
    <<: *vars_dev
    APP: store-frontend
    BUILD_DIR: store_admin
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/
      when: manual
  tags: 
    - shell
  


migrate-dev:
  extends: .migrate-db
  environment:
    name: dev

rollback-dev:
  extends: .rollback-db
  environment:
    name: dev
  
    


deploy-backend-dev:
  extends: .deploy_k8s
  variables:
    <<: *vars_dev
    APP: store-backend
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  tags: 
    - shell
  environment:
    name: dev
    url: https://api-sandbox-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru

deploy-frontend-dev:
  extends: .deploy_k8s
  variables:
    <<: *vars_dev
    APP: store-frontend
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  tags: 
    - shell
  environment:
    name: dev
    url: https://admin-sandbox-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru

# deploy-test:
#   extends: .deploy_k8s  
#   variables:
#     <<: *vars_dev
#     KUBECONFIG: "/home/gitlab-runner/.kube/test-cluster.yaml"
#   tags: 
#     - shell
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
#       when: manual
#     - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
#       when: manual
#   environment:
#     name: test
#     url: https://api-sandbox-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru

swagger-dev:
  extends: .deploy_swagger
  needs: [deploy-backend-dev]
  variables:
    <<: *vars_dev
  tags: 
    - shell
  environment:
    name: dev
    url: https://api-sandbox-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru/swagger
