stages:
  - build
  - migrate
  - deploy
  - swagger


.vars_prod: &vars_prod
  HARBOR_URL: harbor-prod.rbtdigitalmobile.ru
  HARBOR_USER: ${HARBOR_USER_PROD}
  HARBOR_PASS: ${HARBOR_PASSWORD_PROD}
  HARBOR_PROJECT: sandbox
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  RUNTIME_IMAGE: harbor-prod.rbtdigitalmobile.ru/library/proto-java-17:2024-06-18
  KUBE_NAMESPACE: app-${CI_ENVIRONMENT_NAME}
  KUBECONFIG: "/home/gitlab-runner/.kube/prod-mobi-gitlab.yaml"


.vars_dev: &vars_dev
  HARBOR_URL: harbor.rbt.ru
  HARBOR_USER: ${HARBOR_USER_DEV}
  HARBOR_PASS: ${HARBOR_PASSWORD_DEV}
  HARBOR_PROJECT: sandbox
  IMAGE_TAG: ${CI_COMMIT_SHA}
  RUNTIME_IMAGE: harbor.rbt.ru/library/proto-java-17:2024-06-18
  KUBE_NAMESPACE: app-${CI_ENVIRONMENT_NAME}

.docker_build_tpl:
  stage: build
  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - cd $CI_PROJECT_DIR
    - docker login -u ${HARBOR_USER} -p ${HARBOR_PASS} https://${HARBOR_URL}
  after_script:
    - docker image rm $(docker image ls | grep ${HARBOR_URL}/${HARBOR_PROJECT} |  awk '{print$3}') || true
    - docker image prune -f

.deploy_k8s:
  stage: mobi-deploy
  script:
    - chmod +x ./k8s-deploy.sh && ./k8s-deploy.sh

.deploy_swagger:
  stage: mobi-swagger
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  script:
    - helm upgrade swagger-${CI_ENVIRONMENT_NAME} ./swagger --set global.env=${CI_ENVIRONMENT_NAME} --install -n ${KUBE_NAMESPACE}

################################################################################################
################################################################################################
################################################################################################
################################################################################################

build-backend:
  extends: .docker_build_tpl
  variables:
    <<: *vars_dev
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/
      when: manual
  tags: 
    - shell
  script:
    - docker build \
      --tag ${HARBOR_URL}/${HARBOR_PROJECT}/:1.0-SNAPSHOT \
      --build-arg="MODULE_NAME=$${MODULE_NAME:=assembly_web}" \
      --build-arg="MODULE_VERSION=$${MODULE_VERSION:=1.0-SNAPSHOT}" \
      --file Dockerfile \
      .
    - docker push ${HARBOR_URL}/${HARBOR_PROJECT}
    


mobi-deploy-dev:
  extends: .deploy_k8s
  variables:
    <<: *vars_dev
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  tags: 
    - shell
  environment:
    name: dev
    url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru

mobi-deploy-test:
  extends: .deploy_k8s  
  variables:
    <<: *vars_dev
    KUBECONFIG: "/home/gitlab-runner/.kube/test-cluster.yaml"
  tags: 
    - shell
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH =~ /^(devops\/.*)$/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  environment:
    name: test
    url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru

mobi-swagger-dev:
  extends: .deploy_swagger
  needs: [mobi-deploy-dev]
  variables:
    <<: *vars_dev
  tags: 
    - shell
  environment:
    name: dev
    url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru/swagger

mobi-swagger-test:
  extends: .deploy_swagger
  needs: [mobi-deploy-test]
  variables:
    <<: *vars_dev
    KUBECONFIG: "/home/gitlab-runner/.kube/test-cluster.yaml"
  tags: 
    - shell
  environment:
      name: test
      url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru/swagger

mobi-deploy-prod:
  extends: .deploy_k8s
  rules:
    - if: $CI_COMMIT_TAG =~ /^(release\/.*)$/
      when: manual
  tags: 
    - mobi-prod
  variables:
    <<: *vars_prod
    
  environment:
    name: prod
    url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru
  script:
    - chmod +x ./k8s-deploy.sh && ./k8s-deploy.sh

mobi-swagger-prod:
  extends: .deploy_swagger
  rules:
    - if: $CI_COMMIT_TAG =~ /^(release\/.*)$/
      when: manual
  tags: 
    - mobi-prod
  variables:
    <<: *vars_prod
  environment:
    name: prod
    url: https://api-${CI_ENVIRONMENT_NAME}.rbtdigitalmobile.ru/swagger
  script:
    - helm upgrade swagger-${CI_ENVIRONMENT_NAME} ./swagger --set global.env=${CI_ENVIRONMENT_NAME} --install -n ${KUBE_NAMESPACE}
 