app:
  openid:
    client:
      client-id: api
      client-secret: 4Ggxc50xzu5j1qFk5rZ4OPHwvNFXLpNX
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8086
