---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chtmpl.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ pluck .Values.global.env .Values.ingress.hosts | default (pluck "default" .Values.ingress.hosts) | first | default "" | toString | replace "{env}" .Values.global.env }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

  tls:
  - hosts: 
    - {{ pluck .Values.global.env .Values.ingress.hosts | default (pluck "default" .Values.ingress.hosts) | first | default "" | toString | replace "{env}" .Values.global.env }}
    secretName: {{ pluck .Values.global.env .Values.ingress.tls.certname | first | default (pluck "default" .Values.ingress.tls.certname | first ) }}
{{- end }}

---
{{- if hasKey .Values "ingress2" }}
{{- if .Values.ingress2.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress2.name_postfix }}
  labels:
    {{- include "chtmpl.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress2.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ pluck .Values.global.env .Values.ip_whitelist | default (pluck "default" .Values.ip_whitelist) | first }}
spec:
  rules:
    - host: {{ pluck .Values.global.env .Values.ingress2.hosts | default (pluck "default" .Values.ingress2.hosts) | first | default "" | toString | replace "{env}" .Values.global.env }}
      http:
        paths:
          {{- range .Values.ingress2.paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}

  tls:
  - hosts: 
    - {{ pluck .Values.global.env .Values.ingress2.hosts | default (pluck "default" .Values.ingress2.hosts) | first | default "" | toString | replace "{env}" .Values.global.env }}
    secretName: {{ pluck .Values.global.env .Values.ingress2.tls.certname | first | default (pluck "default" .Values.ingress2.tls.certname | first ) }}
{{- end }}
{{- end }}