apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chtmpl.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /back/{{ .Values.probePath | default .Chart.Name }}/actuator/prometheus
    port: http
    scheme: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}