apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}
  labels:
    {{- include "chtmpl.labels" . | nindent 4 }}
data:
  {{- $env := .Values.global.env }}
  GLOBAL_ENVIRONMENT: "{{ $env }}"
  {{- range $k, $v := .Values.configmap }}
    {{- if eq (kindOf $v) "map" }}
  {{ $k }}: "{{ pluck $env $v | default (pluck "default" $v) | first | toString | replace "{env}" $env }}"
    {{- else }}
  {{ $k }}: "{{ $v | toString | replace "{env}" $env }}"
    {{- end }}
  {{- end }}
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  swagger-config-json
  labels:
    {{- include "chtmpl.labels" . | nindent 4 }}
data:
  swagger-config.json: |
  {{- .Files.Get "swagger-config.json" | nindent 4 }}