app:
  openid:
    client:
      client-id: api
      client-secret: 4Ggxc50xzu5j1qFk5rZ4OPHwvNFXLpNX
  minio:
    client:
      endpoint: http://minio.local.example.com
      secret-key: AZitoDkffcEYFYUmV4CGv1jr2fiXWIw4uSvdFlDu
      access-key: y5LeRZ84J4SsenpaIxMl
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: app
    url: jdbc:postgresql://localhost:5432/app
    password: app
server:
  port: 8080
