services:
  app-assembly-web:
    depends_on:
    - env-kafka
    - env-postgres
    - env-keycloak
    - env-minio
    image: store/assembly_web:1.0-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://env-postgres:5432/app
      APP_OPENID_CLIENT_CLIENTID: api
      APP_OPENID_CLIENT_CLIENTSECRET: 4Ggxc50xzu5j1qFk5rZ4OPHwvNFXLpNX
      SPRING_KAFKA_BOOTSTRAP_SERVERS: env-kafka:29092
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_DATASOURCE_USERNAME: app
      APP_MINIO_ACCESS_KEY: y5LeRZ84J4SsenpaIxMl
      APP_MINIO_SECRET_KEY: AZitoDkffcEYFYUmV4CGv1jr2fiXWIw4uSvdFlDu
      APP_MINIO_TARGET_SERVER: http://env-minio:9000
      JAVA_OPTS: -Xmx512m -Xms256m
    restart: unless-stopped
    networks:
      default: {}
    links:
    - env-haproxy:auth.local.example.com
    deploy:
      resources:
        limits:
          memory: 600M
    profiles:
    - app

