services:
  app_assembly_web:
    depends_on:
    - env_kafka
    - env_postgres
    - env_keycloak
    image: store/assembly_web:1.0-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://env_postgres:5432/app
      APP_OPENID_CLIENT_CLIENTID: api
      APP_OPENID_CLIENT_CLIENTSECRET: 4Ggxc50xzu5j1qFk5rZ4OPHwvNFXLpNX
      SPRING_DATASOURCE_USERNAME: app
      SPRING_KAFKA_BOOTSTRAP_SERVERS: env_kafka:29092
      SPRING_DATASOURCE_PASSWORD: app
      JAVA_OPTS: -Xmx512m -Xms256m
    restart: unless-stopped
    networks:
      default: {}
    links:
    - env_haproxy:auth.local.example.com
    deploy:
      resources:
        limits:
          memory: 600M
    profiles:
    - app

