server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /api/gateway_events

spring:
  application:
    name: gateway_events
  config:
    import:
      - classpath:shared-datasource.yaml
      - classpath:shared-security.yaml

springdoc:
  api:
    title: Store
    description: Store Description
    version: 1

firebase:
  config-file: ${FIREBASE_CONFIG_PATH:classpath:firebase-service-account.json}
