server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /api/gateway_events

spring:
  application:
    name: gateway_events
  config:
    import:
      - classpath:shared-datasource.yaml
      - classpath:gateway_events.yaml

springdoc:
  api:
    title: Store
    description: Store Description
    version: 1
